[versions]
agp = "8.5.2"
kotlin = "2.0.20"
composeBom = "2024.09.03"
activityCompose = "1.9.2"
ktor = "2.3.12"
serialization = "1.7.2"
securityCrypto = "1.1.0-alpha06"
googleCodeScanner = "16.1.0"
biometric = "1.1.0"
androidxCredentials = "1.5.0"
playServicesIdentityCredentials = "16.0.0-alpha08"
junit = "4.13.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
google-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "googleCodeScanner" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
play-services-identity-credentials = { module = "com.google.android.gms:play-services-identity-credentials", version.ref = "playServicesIdentityCredentials" }
junit = { module = "junit:junit", version.ref = "junit" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material3 = { module = "androidx.compose.material3:material3" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
